<?php

use Illuminate\Database\Seeder;

class SkemaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kelas = [
        	array( 'kelas' => '10 MIA'),
        	array( 'kelas' => '10 IIS'),
        	array( 'kelas' => '11 MIA'),
        	array( 'kelas' => '11 IIS'),
        	array( 'kelas' => '12 MIA'),
        	array( 'kelas' => '12 IIS'),
        ];

        $mapel = [
            array( 'kelas_id' => 1, 'mapel' => 'Matematika'),
            array( 'kelas_id' => 1, 'mapel' => 'Bahasa Indonesia'),
            array( 'kelas_id' => 1, 'mapel' => 'Kimia'),
            array( 'kelas_id' => 1, 'mapel' => 'Biologi'),
            array( 'kelas_id' => 1, 'mapel' => 'Bahasa Inggris'),
            array( 'kelas_id' => 1, 'mapel' => 'Fisika'),
            
            array( 'kelas_id' => 2, 'mapel' => 'Matematika'),
            array( 'kelas_id' => 2, 'mapel' => 'Bahasa Indonesia'),
            array( 'kelas_id' => 2, 'mapel' => 'Sosiologi'),
            array( 'kelas_id' => 2, 'mapel' => 'Geografi'),
            array( 'kelas_id' => 2, 'mapel' => 'Bahasa Inggris'),
            array( 'kelas_id' => 2, 'mapel' => 'Ekonomi'),
            
            array( 'kelas_id' => 3, 'mapel' => 'Matematika'),
            array( 'kelas_id' => 3, 'mapel' => 'Bahasa Indonesia'),
            array( 'kelas_id' => 3, 'mapel' => 'Kimia'),
            array( 'kelas_id' => 3, 'mapel' => 'Biologi'),
            array( 'kelas_id' => 3, 'mapel' => 'Bahasa Inggris'),
            array( 'kelas_id' => 3, 'mapel' => 'Fisika'),
            
            array( 'kelas_id' => 4, 'mapel' => 'Matematika'),
            array( 'kelas_id' => 4, 'mapel' => 'Bahasa Indonesia'),
            array( 'kelas_id' => 4, 'mapel' => 'Sosiologi'),
            array( 'kelas_id' => 4, 'mapel' => 'Geografi'),
            array( 'kelas_id' => 4, 'mapel' => 'Bahasa Inggris'),
            array( 'kelas_id' => 4, 'mapel' => 'Ekonomi'),
            
            array( 'kelas_id' => 5, 'mapel' => 'Matematika'),
            array( 'kelas_id' => 5, 'mapel' => 'Bahasa Indonesia'),
            array( 'kelas_id' => 5, 'mapel' => 'Kimia'),
            array( 'kelas_id' => 5, 'mapel' => 'Biologi'),
            array( 'kelas_id' => 5, 'mapel' => 'Bahasa Inggris'),
            array( 'kelas_id' => 5, 'mapel' => 'Fisika'),
            
            array( 'kelas_id' => 6, 'mapel' => 'Matematika'),
            array( 'kelas_id' => 6, 'mapel' => 'Bahasa Indonesia'),
            array( 'kelas_id' => 6, 'mapel' => 'Sosiologi'),
            array( 'kelas_id' => 6, 'mapel' => 'Geografi'),
            array( 'kelas_id' => 6, 'mapel' => 'Bahasa Inggris'),
            array( 'kelas_id' => 6, 'mapel' => 'Ekonomi'),
            
        ];

        $bab = [

            array( 'mapel_id' => 1, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 1, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 1, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 1, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 1, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 1, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 1, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 1, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 1, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 1, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 1, 'bab' => 'Bab 11'),

            array( 'mapel_id' => 2, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 2, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 2, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 2, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 2, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 2, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 2, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 2, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 2, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 2, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 2, 'bab' => 'Bab 11'),

            array( 'mapel_id' => 3, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 3, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 3, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 3, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 3, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 3, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 3, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 3, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 3, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 3, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 3, 'bab' => 'Bab 11'),

            array( 'mapel_id' => 4, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 4, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 4, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 4, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 4, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 4, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 4, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 4, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 4, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 4, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 4, 'bab' => 'Bab 11'),

            array( 'mapel_id' => 5, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 5, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 5, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 5, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 5, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 5, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 5, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 5, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 5, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 5, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 5, 'bab' => 'Bab 11'),

            array( 'mapel_id' => 6, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 6, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 6, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 6, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 6, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 6, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 6, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 6, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 6, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 6, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 6, 'bab' => 'Bab 11'),

            array( 'mapel_id' => 7, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 7, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 7, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 7, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 7, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 7, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 7, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 7, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 7, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 7, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 7, 'bab' => 'Bab 11'),

            array( 'mapel_id' => 8, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 8, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 8, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 8, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 8, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 8, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 8, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 8, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 8, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 8, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 8, 'bab' => 'Bab 11'),

            array( 'mapel_id' => 9, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 9, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 9, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 9, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 9, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 9, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 9, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 9, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 9, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 9, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 9, 'bab' => 'Bab 11'),

            array( 'mapel_id' => 10, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 10, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 10, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 10, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 10, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 10, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 10, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 10, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 10, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 10, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 10, 'bab' => 'Bab 11'),

            array( 'mapel_id' => 11, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 11, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 11, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 11, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 11, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 11, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 11, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 11, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 11, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 11, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 11, 'bab' => 'Bab 11'),

            array( 'mapel_id' => 12, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 12, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 12, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 12, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 12, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 12, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 12, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 12, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 12, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 12, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 12, 'bab' => 'Bab 11'),

            array( 'mapel_id' => 13, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 13, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 13, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 13, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 13, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 13, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 13, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 13, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 13, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 13, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 13, 'bab' => 'Bab 11'),

            array( 'mapel_id' => 14, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 14, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 14, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 14, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 14, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 14, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 14, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 14, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 14, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 14, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 14, 'bab' => 'Bab 11'),

            array( 'mapel_id' => 15, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 15, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 15, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 15, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 15, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 15, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 15, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 15, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 15, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 15, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 15, 'bab' => 'Bab 11'),

            array( 'mapel_id' => 16, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 16, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 16, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 16, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 16, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 16, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 16, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 16, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 16, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 16, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 16, 'bab' => 'Bab 11'),

            array( 'mapel_id' => 17, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 17, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 17, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 17, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 17, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 17, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 17, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 17, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 17, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 17, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 17, 'bab' => 'Bab 11'),

            array( 'mapel_id' => 18, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 18, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 18, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 18, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 18, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 18, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 18, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 18, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 18, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 18, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 18, 'bab' => 'Bab 11'),

            array( 'mapel_id' => 19, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 19, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 19, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 19, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 19, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 19, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 19, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 19, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 19, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 19, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 19, 'bab' => 'Bab 11'),

            array( 'mapel_id' => 20, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 20, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 20, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 20, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 20, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 20, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 20, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 20, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 20, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 20, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 20, 'bab' => 'Bab 11'),

            array( 'mapel_id' => 21, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 21, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 21, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 21, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 21, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 21, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 21, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 21, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 21, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 21, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 21, 'bab' => 'Bab 11'),

            array( 'mapel_id' => 22, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 22, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 22, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 22, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 22, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 22, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 22, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 22, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 22, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 22, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 22, 'bab' => 'Bab 11'),
            
            array( 'mapel_id' => 23, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 23, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 23, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 23, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 23, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 23, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 23, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 23, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 23, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 23, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 23, 'bab' => 'Bab 11'),
            
            array( 'mapel_id' => 24, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 24, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 24, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 24, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 24, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 24, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 24, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 24, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 24, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 24, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 24, 'bab' => 'Bab 11'),
            
            array( 'mapel_id' => 25, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 25, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 25, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 25, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 25, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 25, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 25, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 25, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 25, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 25, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 25, 'bab' => 'Bab 11'),
            
            array( 'mapel_id' => 26, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 26, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 26, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 26, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 26, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 26, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 26, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 26, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 26, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 26, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 26, 'bab' => 'Bab 11'),
            
            array( 'mapel_id' => 27, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 27, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 27, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 27, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 27, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 27, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 27, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 27, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 27, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 27, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 27, 'bab' => 'Bab 11'),
            
            array( 'mapel_id' => 28, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 28, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 28, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 28, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 28, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 28, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 28, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 28, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 28, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 28, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 28, 'bab' => 'Bab 11'),
            
            array( 'mapel_id' => 29, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 29, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 29, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 29, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 29, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 29, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 29, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 29, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 29, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 29, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 29, 'bab' => 'Bab 11'),
            
            array( 'mapel_id' => 30, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 30, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 30, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 30, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 30, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 30, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 30, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 30, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 30, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 30, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 30, 'bab' => 'Bab 11'),
            
            array( 'mapel_id' => 31, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 31, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 31, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 31, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 31, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 31, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 31, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 31, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 31, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 31, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 31, 'bab' => 'Bab 11'),
            
            array( 'mapel_id' => 32, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 32, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 32, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 32, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 32, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 32, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 32, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 32, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 32, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 32, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 32, 'bab' => 'Bab 11'),
            
            array( 'mapel_id' => 33, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 33, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 33, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 33, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 33, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 33, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 33, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 33, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 33, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 33, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 33, 'bab' => 'Bab 11'),
            
            array( 'mapel_id' => 34, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 34, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 34, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 34, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 34, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 34, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 34, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 34, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 34, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 34, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 34, 'bab' => 'Bab 11'),
            
            array( 'mapel_id' => 35, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 35, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 35, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 35, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 35, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 35, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 35, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 35, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 35, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 35, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 35, 'bab' => 'Bab 11'),
            
            array( 'mapel_id' => 36, 'bab' => 'Bab 1'), 
            array( 'mapel_id' => 36, 'bab' => 'Bab 2'), 
            array( 'mapel_id' => 36, 'bab' => 'Bab 3'), 
            array( 'mapel_id' => 36, 'bab' => 'Bab 4'), 
            array( 'mapel_id' => 36, 'bab' => 'Bab 5'),
            array( 'mapel_id' => 36, 'bab' => 'Bab 6'),
            array( 'mapel_id' => 36, 'bab' => 'Bab 7'),
            array( 'mapel_id' => 36, 'bab' => 'Bab 8'),
            array( 'mapel_id' => 36, 'bab' => 'Bab 9'),
            array( 'mapel_id' => 36, 'bab' => 'Bab 10'),
            array( 'mapel_id' => 36, 'bab' => 'Bab 11'),
        ];

        DB::table('kelas')->insert($kelas);
        DB::table('mapels')->insert($mapel);
        DB::table('babs')->insert($bab);
    }
}
